[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm --directory ~"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[magnify]
factor = 2.0
